spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}

#payment:
#  service: Razorpay
#
#email:
#  host: Localhost
#  port: 8080
#
#paytm:
#  name: Paytm
#  account:
#    balance: 10000
#    loan: 250000